### PR TITLE
Added notches for screws and bumpons

### PR DESCRIPTION
**Pull request by IvoGoman**
- Added notches for the screws located on the underside of the top of the PCB.
- Added notches for up to 1cm diameter bumpons on the bottom side of the case 

The notches for the screws make the PCB fit flat in the case with USB connector almost centered in its opening.

### CODE REVIEW

**Comment by BenRoe** [comment]
Hi,
thank you for your effort. The inner notches are not necessary. Please check the image.
I used 4 other M2x4mm screws.
You can also use the M2x10mm screws from the top. The screw sticks out from below. Screw the 5mm space from the bottom on this screws.

IMG_7428

Can you move your case in a subfolder with your github name? Then i can merge it and we have both versions.

**Comment by BenRoe** [comment]
... and if possible add a readme.md with a small description what changed and some images.
That would be lovely and useful for other people.

**Comment by IvoGoman** [comment]
Hi,
thanks for the feedback. I have updated the PR.
The remarks for the 4mm screws make sense, but I only have the M2 screws that came with the kit at hand.
I added this as well to the readme.
I am not sure if I misunderstood you but using the 10mm M2 screws with the 5mm spacer will not work due to the height of the capacitor (C3).

**Comment by BenRoe** [comment]
@IvoGoman thanks for your changes. Will merge it.
From top to bottom (M4x4 screw -> acrylic guard plate -> 8mm or 10mm spacer -> pcb -> M2x4 screw)

**Pull request merged**
